import html as html_escape
from pathlib import Path
from datetime import datetime
from xhtml2pdf import pisa

def _generate_pdf_html(results: list, target_url: str) -> str:
    """Build a PDF-specific layout: one block per finding rather than a wide table.
    xhtml2pdf's table/column-width support isn't reliable with long unbroken strings
    (URLs, curl commands), so a table copied from the HTML report renders with
    overlapping text — per-finding blocks avoid that entirely."""
    safe_target_url = html_escape.escape(target_url)
    html = f"""
    <html>
    <head>
    <style>
        body {{ font-family: Helvetica, Arial, sans-serif; font-size: 10pt; }}
        h1 {{ color: #d32f2f; font-size: 16pt; }}
        .finding {{ border: 1px solid #ccc; padding: 10px; margin-bottom: 14px; }}
        .finding-title {{ font-size: 11pt; font-weight: bold; color: #d32f2f; margin-bottom: 6px; }}
        .field-label {{ font-weight: bold; }}
        .field {{ margin-bottom: 4px; word-wrap: break-word; }}
        .curl {{
            font-family: Courier, monospace; font-size: 7pt; background-color: #f5f5f5;
            padding: 6px; word-wrap: break-word; word-break: break-all;
        }}
        .screenshot {{ max-width: 280px; margin-top: 6px; }}
    </style>
    </head>
    <body>
        <h1>PyXSSHunter XSS Scan Report</h1>
        <p><span class="field-label">Target:</span> {safe_target_url}</p>
        <p><span class="field-label">Scan Time:</span> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><span class="field-label">Findings:</span> {len(results)} potential XSS issues</p>
    """
    for i, r in enumerate(results, 1):
        screenshot_b64 = r.get("screenshot_b64")
        screenshot_html = (
            f'<img class="screenshot" src="data:image/png;base64,{screenshot_b64}">'
            if screenshot_b64 else ""
        )
        html += f"""
        <div class="finding">
            <div class="finding-title">#{i} &mdash; {html_escape.escape(r.get('type', 'Reflected'))} XSS</div>
            <div class="field"><span class="field-label">URL:</span> {html_escape.escape(r['url'])}</div>
            <div class="field"><span class="field-label">Payload:</span> {html_escape.escape(r['payload'])}</div>
            <div class="field"><span class="field-label">Status:</span> {r['status']}</div>
            <div class="field"><span class="field-label">Evidence:</span> {html_escape.escape(r['evidence'])}</div>
            <div class="field"><span class="field-label">curl PoC:</span></div>
            <div class="curl">{html_escape.escape(r.get('curl_command', ''))}</div>
            {screenshot_html}
        </div>
        """
    html += """
        <p><i>Generated by PyXSSHunter - For authorized testing only</i></p>
    </body>
    </html>
    """
    return html

def generate_pdf_report(results: list, target_url: str, output_path: Path) -> str:
    """Render findings to a PDF file at output_path"""
    pdf_html = _generate_pdf_html(results, target_url)
    with open(output_path, "wb") as f:
        result = pisa.CreatePDF(pdf_html, dest=f)

    if result.err:
        raise RuntimeError(f"Failed to generate PDF report ({result.err} error(s))")

    return str(output_path)

def save_pdf_report(results: list, target_url: str, output_dir: Path, base_name: str, timestamp: str = None) -> str:
    """Render and save the PDF report, mirroring reporter.save_report's naming"""
    timestamp = timestamp or datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = output_dir / f"{base_name}_{timestamp}.pdf"
    return generate_pdf_report(results, target_url, filename)
