from pathlib import Path
from datetime import datetime
from urllib.parse import urlparse

def generate_html_report(results: list, target_url: str) -> str:
    """Generate a simple but nice HTML report"""
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>PyXSSHunter Report - {target_url}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            h1 {{ color: #d32f2f; }}
            table {{ border-collapse: collapse; width: 100%; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f5f5f5; }}
            .vulnerable {{ color: red; font-weight: bold; }}
        </style>
    </head>
    <body>
        <h1>PyXSSHunter XSS Scan Report</h1>
        <p><strong>Target:</strong> {target_url}</p>
        <p><strong>Scan Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><strong>Findings:</strong> {len(results)} potential XSS issues</p>
        
        <table>
            <tr>
                <th>#</th>
                <th>Vulnerable URL</th>
                <th>Payload</th>
                <th>Status</th>
                <th>Evidence</th>
            </tr>
    """
    for i, r in enumerate(results, 1):
        html += f"""
            <tr>
                <td>{i}</td>
                <td class="vulnerable">{r['url']}</td>
                <td>{r['payload']}</td>
                <td>{r['status']}</td>
                <td>{r['evidence']}</td>
            </tr>
        """
    html += """
        </table>
        <p><em>Generated by PyXSSHunter • For authorized testing only</em></p>
    </body>
    </html>
    """
    return html

def save_report(html_content: str, output_dir: Path, base_name: str) -> str:
    """Save report to file and return full path"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = output_dir / f"{base_name}_{timestamp}.html"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(html_content)

    return str(filename)